[custom.all.fix-whitespace]
type   = "local"
path   = "."
ipkg   = "fix-whitespace.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-util.ipkg"

[custom.all.elab-pretty]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:main"
ipkg   = "elab-pretty.ipkg"

[custom.all.filepath]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-filepath"
commit = "latest:main"
ipkg   = "filepath.ipkg"
